.DEFAULT_GOAL := build

.PHONY: build
build:
	pnpm build

.PHONY: facebook
facebook:
	pnpm run:facebook

.PHONY: facebook-chrome
facebook-chrome:
	pnpm run:facebook-chrome

.PHONY: auth
auth:
	pnpm run:auth

.PHONY: save-post
save-post:
	./scripts/save-post.sh
